name: Setup Dependencies
description: Setup base dependenceies for the project


runs: 
  using: 'composite'
  steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Relies on the pnpm version defined in the packageManager field in package.json
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run-install: false

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm i
    