name: Deploy Projects
description: Deploy projects to production

inputs:
  ZEPHYR_API_KEY: 
    required: true
    type: string


runs: 
  # A composite action combines multiple actions or steps into a single reusable action
  # It allows us to create a sequence of steps that can be reused across different workflows
  using: 'composite'
  
  steps: 

    - name: set-sha-action
      id: set-sha-action
      uses: nrwl/nx-set-shas@v4

    # Run quality checks and fail the deployment if any of the checks fail
    - name: Run affected E2E Tests
      shell: bash
      run: |
        pnpm nx affected -t e2e --parallel 10 --nxBail true


    - name: Check if E2E test reports created
      id: check_folder
      shell: bash
      run: |
        if [ -d "dist/playwright-report" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - uses: actions/upload-artifact@v4
      if: steps.check_folder.outputs.exists == 'true'
      with: 
          name: playwright-report
          path: dist/playwright-report/*/playwright-report
          retention-days: 10
          overwrite: true

    - name: Deploy with Zephyr
      shell: bash
      continue-on-error: true
      env: 
        ZEPHYR_API_KEY: ${{ inputs.ZEPHYR_API_KEY }}
        WITH_ZE: "1"
      run: |
        pnpm nx affected -t build --parallel 10 --nxBail --output-style static
       
  