name: Deploy Projects
description: Deploy projects to production

inputs:
  ZEPHYR_API_KEY: 
    required: true
    type: string


runs: 
  # A composite action combines multiple actions or steps into a single reusable action
  # It allows us to create a sequence of steps that can be reused across different workflows
  using: 'composite'
  
  steps: 

    - name: set-sha-action
      id: set-sha-action
      uses: nrwl/nx-set-shas@v4

    # Run quality checks and fail the deployment if any of the checks fail
    - name: Run affected E2E Tests
      id: affected-e2e-tests
      shell: bash
      run: |
        node ./.github/scripts/nx-log-parser.js e2e

    - name: Display E2E Summary
      uses: mshick/add-pr-comment@v2
      with:
        message-id: e2e-summary
        message-path: ./nx-report.md


    - name: Check if E2E test reports created
      id: check_folder
      shell: bash
      run: |
        if [ -d "dist/playwright-report" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - uses: actions/upload-artifact@v4
      if: steps.check_folder.outputs.exists == 'true'
      with: 
          name: playwright-report
          path: dist/playwright-report/*/playwright-report
          retention-days: 10
          overwrite: true

    - name: Quality Check Status
      if: steps.affected-e2e-tests.outputs.success == 'false'
      shell: bash
      run: exit 1

    - name: Deploy with Zephyr
      id: deploy-with-zephyr
      shell: bash
      continue-on-error: true
      env: 
        ZEPHYR_API_KEY: ${{ inputs.ZEPHYR_API_KEY }}
        WITH_ZE: "1"
      run: |
        node ./.github/scripts/nx-log-parser.js build

    - name: Display Build Summary
      uses: mshick/add-pr-comment@v2
      with:
        message-id: deployment-build-summary
        message-path: ./nx-report.md

    - name: Deployment Workflow Status
      if: steps.deploy-with-zephyr.outputs.success == 'false'
      shell: bash
      run: exit 1
       
  