name: Deploy to Production

on:
  # Trigger on PR merge to main
  pull_request:
    types: [closed]
    branches:
      - main

  # Trigger on direct push to main
  push:
    branches:
      - main

jobs:
  deploy-prod:
    # For PR trigger: only run if PR was merged
    # For push trigger: always run
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-e2e-dependencies

      - name: Run E2E and Deploy to Prod
        uses: ./.github/actions/deploy-projects
        with:
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
