name: Quality Checks
description: Run quality checks on the project

inputs:
  github-token: 
    required: true
    type: string


runs: 
  # A composite action combines multiple actions or steps into a single reusable action
  # It allows us to create a sequence of steps that can be reused across different workflows
  using: 'composite'
  
  steps: 

    - name: set-sha-action
      id: set-sha-action
      uses: nrwl/nx-set-shas@v4

    # Run quality checks and fail the deployment if any of the checks fail
    - name: Run Quality Checks
      shell: bash
      run: |
        pnpm nx affected -t lint typecheck test e2e --parallel 10 --nxBail true

    - uses: actions/upload-artifact@v4
      with: 
          name: playwright-report
          path: dist/*/playwright-report/
          retention-days: 30

    - name: Deploy with Zephyr
      shell: bash
      continue-on-error: true
      env: 
        ZEPHYR_API_KEY=${{ secrets.ZEPHYR_API_KEY }}
        WITH_ZE: "1"
      run: |
        pnpm nx run affected -t build --parallel 10 --nxBail --output-style static
       
  