name: Quality Checks
description: Run quality checks on the project

inputs:
  ZE_SECRET_TOKEN: 
    required: true
    type: string


runs: 
  # A composite action combines multiple actions or steps into a single reusable action
  # It allows us to create a sequence of steps that can be reused across different workflows
  using: 'composite'
  
  steps: 

    - name: set-sha-action
      id: set-sha-action
      uses: nrwl/nx-set-shas@v4

    # Run quality checks and fail the deployment if any of the checks fail
    - name: Run Quality Checks
      id: quality-checks
      shell: bash
      continue-on-error: true
      run: |
        node ./.github/scripts/nx-log-parser.js lint typecheck test e2e

    - name: Display Quality Check Summary
      uses: mshick/add-pr-comment@v2
      with:
        message-id: quality-check-summary
        message-path: ./nx-report.md

    - name: Check if E2E test reports created
      id: check_folder
      shell: bash
      run: |
        if [ -d "dist/playwright-report" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - uses: actions/upload-artifact@v4
      if: steps.check_folder.outputs.exists == 'true'
      with: 
          name: playwright-report
          path: dist/playwright-report/*/playwright-report
          retention-days: 10
          overwrite: true

    - name: Beployment Workflow Status
      if: steps.quality-checks.outputs.success == 'false'
      shell: bash
      run: exit 1

    - name: Deploy with Zephyr
      shell: bash
      continue-on-error: true
      id: deploy-with-zephyr
      env: 
        ZE_SECRET_TOKEN: ${{ inputs.ZE_SECRET_TOKEN }}
      run: |
       node ./.github/scripts/nx-log-parser.js build
    
    - name: Display Build Summary
      uses: mshick/add-pr-comment@v2
      with:
        message-id: build-summary
        message-path: ./nx-report.md

    - name: Beployment Workflow Status
      if: steps.deploy-with-zephyr.outputs.success == 'false'
      shell: bash
      run: exit 1
       
  